site_name: Weave.jl - Scientific Reports Using Julia
site_author: Matti Pastell
copyright: Matti Pastell 2016
repo_url: https://github.com/mpastell/Weave.jl

theme: material

#extra:
#  palette:
#    primary: 'indigo'
#    accent:  'blue'

extra_css:
  - assets/Documenter.css

#extra_javascript:
#  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite(css_class=code)
#  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Getting started: getting_started.md
  - Using Weave: usage.md
  - Publishing scripts: publish.md
  - Chunk options: chunk_options.md
  - Working with Jupyter notebooks: notebooks.md
  - Function index: function_index.md
